dataset: cub200

model: icarl
convnet: resnet18

sampler: balance

eval_kappa: True

memory_size: 100
fixed_memory: True

convnet_config:
  last_relu: True
  pretrained: True
  nf: 64
  initial_kernel: 7

classifier_config:
  scaling: 1
  gamma: 1
  type: cosine
  proxy_per_class: 1
  distance: cosine

postprocessor_config:
  initial_value: 1.0
  type: learned_scaling  

classification_loss:
  type: ce
  
epochs: 150 #60
lr: 0.1
weight_decay: 0.0005
scheduling:
  - 50
  - 100
lr_decay: 0.1
optimizer: sgd

groupwise_factors:
  convnet: [0.1, 0.01]

no_progressbar: True
