dataset: ham10000

model: ucir
convnet: resnet18

sampler: balance

eval_type: cnn

convnet_config:
  last_relu: True
  pretrained: True
  nf: 64
  initial_kernel: 7

memory_size: 140
fixed_memory: True

classifier_config:
  scaling: 1
  gamma: 1
  type: cosine
  proxy_per_class: 1
  distance: cosine

less_forget:
  scheduled_factor: true
  lambda: 5

postprocessor_config:
  initial_value: 1.0
  type: learned_scaling

ranking_loss:
  factor: 1.0
  nb_negatives: 2
  margin: 0.5

groupwise_factors:
  old_weights: 0.
  convnet: 0.01

epochs: 100 #60
lr: 0.1
weight_decay: 0.0005
scheduling:
  type: step
  epochs: [40, 80]
  gamma: 0.1
lr_decay: 0.1
optimizer: sgd

weight_generation:
  type: imprinted

no_progressbar: True
