dataset: diabetic

model: der
convnet: dynaresnet18

sampler: balance

eval_type: cnn
eval_kappa: True

convnet_config:
  last_relu: True
  pretrained: True
  nf: 64
  initial_kernel: 7
  shared_features: 0

memory_size: 100
fixed_memory: True

reset_classifier: True

aux_classifier_config:
  scaling: 1
  gamma: 1
  type: cosine
  proxy_per_class: 1
  distance: cosine

classifier_config:
  scaling: 1
  gamma: 1
  type: cosine
  proxy_per_class: 1
  distance: cosine

postprocessor_config:
  initial_value: 1.0
  type: learned_scaling

classification_loss:
  gamma: 0.0
  beta: 0.0
  start_old: 0
  schedule_old: 0
  gamma_old: 2.0
  beta_old: 0.999

distillation_loss:
  factor: 0.0
  T: 2.0

auxillary_loss:
  factor: 1.0
  n+1: True
  gamma: 0.0
  beta: 0.0

ranking_loss:
  factor: 0.0
  nb_negatives: 1
  margin: 0.4

finetuning_config:
  tuning: classifier_scale
  lr: 0.1
  epochs: 30
  temperature: 5.0
  scheduling:
    type: step
    epochs: [15]
    gamma: 0.1

groupwise_factors:
  convnet_new: [0.1, 0.01]
  convnet_old: 0.

pretrain_epochs: 150
epochs: 150 #60
lr: 0.1
weight_decay: 0.0005
pretrain_scheduling:
  type: step
  epochs: [50, 100]
  gamma: 0.1
scheduling:
  type: step
#   epochs: [80, 160]
  epochs: [10, 40, 80] 
#   epochs: [20, 70, 100]  
  gamma: 0.1
lr_decay: 0.1
optimizer: sgd

weight_generation:
  type: imprinted

no_progressbar: True
